service: server
frameworkVersion: "3"

provider:
  name: aws
  httpApi:
    payload: "2.0"
    disableDefaultEndpoint: false
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizer
  runtime: nodejs18.x
  profile: Yumyumgimmisum
  region: eu-north-1
  iam:
    role: arn:aws:iam::277117890175:role/Yumyumadminrole
  deploymentMethod: direct

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getMenu:
    handler: functions/menuFunctions/getMenu/index.handler
    events:
      - httpApi:
          path: /api/menu
          method: GET
  addOrder:
    handler: functions/orderFunctions/addOrder/index.handler
    events:
      - httpApi:
          path: /api/order
          method: POST
  getAllOrders:
    handler: functions/orderFunctions/getAllOrders/index.handler
    events:
      - httpApi:
          path: /api/orders
          method: GET
          authorizer:
            name: customAuthorizer
            type: request
  getOrder:
    handler: functions/orderFunctions/getOrder/index.handler
    events:
      - httpApi:
          path: /api/order/{id}
          method: GET
  updateOrder:
    handler: functions/orderFunctions/updateOrder/index.handler
    events:
      - httpApi:
          path: /api/order/{id}
          method: PUT
  authorizer:
    handler: functions/authorizer/index.authorizer

resources:
  Resources: 
    menudb:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: menudb
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    orderdb:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: orderdb
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST